INSERT INTO CONTRACTOR (FIRST_NAME, LAST_NAME, PERSONAL_NUMBER) VALUES ('FN1', 'LN1', '00001');
INSERT INTO CONTRACTOR (FIRST_NAME, LAST_NAME, PERSONAL_NUMBER) VALUES ('FN2', 'LN2', '00002');
INSERT INTO CONTRACTOR (FIRST_NAME, LAST_NAME, PERSONAL_NUMBER) VALUES ('FN3', 'LN3', '00003');
INSERT INTO CONTRACTOR (FIRST_NAME, LAST_NAME, PERSONAL_NUMBER) VALUES ('FN4', 'LN4', '00004');
INSERT INTO CONTRACTOR (FIRST_NAME, LAST_NAME, PERSONAL_NUMBER) VALUES ('FN5', 'LN5', '00005');